language: node_js
services:
- postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
- psql -c 'CREATE DATABASE find_and_adopt_test;' -U postgres
env:
  global:
     secure: "p3VEbqRbSj2a0LJgnEXaExB5lNXvOQaP8PO2Qgr0sWCjzWx+9DDjj1prXro6CJGUaDHkKPlbGiLMm/HW2N9s15a05kLV2FyCmzp+XZYI971q/iH7ILu6qWwsMEhCIDS28lrfLhPJJT6SSNPBsLBxc+7tUIaMUWyU99WtReilDvVTTccXd9mhuQVdG2QTJaROkFYyJB5ifrwH2gI/7Igjm7q2snHYwxB6RkpUfukQJ4I8lVVMtXkIBO8rTJFyrd4rLoAfQZTt9phP78IXMqTUxpXxhDEd5ZLiKVATGqhN53RRN7Sjb9/G/bflqmsptZSoMlJkmqFQ7MafesA4Q3juCuzYTO0zQPej9OTbYVdSgbiqAS9PTE+2cQJdaUGFJrMLAuw0M/q3L/xrdyhhtEddij55ntRaBKCtNO+uVAXdyqqAaGJmtSQeYlpeINlSjhOK0Hsh38lD7/Kh4Lg8BIhS4Zfj00YqX02+zy0GpuZWQdsmeJ/PdsLr7KTygjf8KE2KkwpTp4joymjz/pZGUwSPblDzxI7ws0DIxAEv5uUJu0ssIsFk1a/que15+ZsBl2lgZlcVO/AaXmUgAKN7lpWVIJLAu90m/mtASJDaPJ+CdZmv8ORuC81CeO/yiAnv75E5HDLJfzKGSaSPS1IlqrXWgWdMPJOfbXIcC4cZPdtxV7w="
     secure: "EgKV4H4y9fJlCSAgjAofvHlZNrRi7lNRdt2D6CyYW7jLzIGyuSKfJVFGZcK0CKGCm8xerxtyAK0vICQzgI016u2HHL+AERdOTrQcKp/BBnB05GnwkbwPsyRizesMoVnRt/s/XBl8XtFzO1+YpPlb/WElWfcR7mBai6qeXyV81JeEG1QYobSGvislcl2w8pvGJhGaAaFtu//xswr44MIANvuC6/dX0LN1l4GVL9HGyeIPzpE9kqKO1kuqdlZc1T6033HuNWBKbaSG1zx9fwkjl8HTh1/c+IUkbhWq+8AMmjiTQ6/2xP/rFyn3dZ5hNLbGNm/6mkkq+MQrxaeyiYijEWyf+ftSBqubJOKOarw0wGHDKbwQHs8KGKjZg4RaN8AOZUARvFYvBFVXX5QHOjGSxLfscd4LrGfNFwJQGSKsiK1+5GYR9219aXpg1a6Zt/1F8vB/K/Iv+XPF3lkZqX+iGqCHgwsWr/fcFV3pZLLTGIzJRYOGZi3cjKGtO74b1L/rLaa8QUfwBd+ndbVHS06JbWmwud56qnU26PTmNXkD5buovZCZZaAhbk/6/MONOp14wQt0ApaGq0JB4spFBrLoe4Sy5I040LokpYwIozFFaJJXzuwV1L1a371PQr0LBTyEMMgTN0FJuaVy+CmyqyxFfjQQrhi0G0NU54eWeL0j6h0="
