language: node_js
services:
- postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
- psql -c 'CREATE DATABASE claro_device_test;' -U postgres
env:
  global:
    - secure: wzyDUnCryWp3DiybWNUHFStbQu9XSYlpF8D/zSZN551+gRy7KpIhP7hwbUpI3UwaMsxJsOQqGhaLOATzvo/KjM2LYiyKzjK2DiqxhXbQHRC3ofocZR6SsygMMqDEO9l+mbvMK+SGfic6mGUasI4Y15Nw6K2qlCJk3J1ewmQXOd4AfLA3369L2WrfdYYs2gvRx7vcQICeBqabt/NmYmqFjqUn7bHZAiBkt1Xx13YGpIHSInXWEjgJp71G/92DGWC1tKw5veaEwCtmjQU1KXzLwDCi5buSSa1Bg8+e7RpwpFewe2CJ0L7LkODVTvEZGjQtnCypAp6yV8H3MPgK1U6WQzDp4AkQLnMWzmHJnpipCBFEFErlD5a2vQpi66COXECI7XPemnmbRblxwNQF1DVLEFPBMXfzPcBQUJJhKwrEoh57yCpzfdQQdBK0OmDOreUzGpRaIYAGPuRes7Czdi8UXgAy30tXKqK3D58oW8XgVH+H8zOkYWpSgkF3Y7xtHs2HAgXu6hnp4gKBG2QcmDHKlhaVoR4BzSeu8xKDehcXG3tEwdczFytbwZLNdv06gFKSL7XvYSV6jEmNQhYYO2Eq2Pf3pR5q9Z74BkMQgHbRdYOmskkYvRoab0YHCvFzpl38GeJlVyvaDhBIpPXq/58HeI3TfKU5LUVqNSJ1p5eKGfA=
    - secure: "CyTQbTun9JoLC4oRhNpLMubdHzhG7fgl3Vo1zlKRo9K6VwaKPrmWZov1PIeX50mGSKgfCNldUh+73BKpexQ/edAL9hXs1q2HVqjdAiUp/x8LHDvw+LtJeEyOYnrOFPQ+VhzR+qxP82RxAaivoii+NEH0foJ6kVxCXxe5vMjshRuaKtAzwn95Dfj5tpl7gm781aiKN4BL20ucDO7ZzsJo7Y9DBauhWS4K611+tQS+mhAUTI1QmkfOmFcnuO/UUBaJr2eUdAt/4MRn6r73fl0KDx6boHZwpE2Ke9r/lr78Y+8GAYG7TIEmB20yWhYlEFaJPe7lDoThjk2r/mIlZRZWoQ/8xN/mmfoo0fY2a3udbsG74o+WZn/6Kg5NPYWdMUK68gh0LWrQmbOqgv7nTeVST+6qjqTmDjOeHprTKao81JtYgrcte1Xy+t/tttQXahZx722vmgxca7YtqGM49zkk8VoFHanzBRV4ZekCa+oawuFn7wQrjLnRRo9R7J4PQJ/Iu4ehfNLK3Jjdc+Z1QZy4i50kwCqrwSd/bqLl7ejGF0x07Z9dj/s9+RXWqyYY9IxgS4zbCwbYLtZX0iR1ZVy8WlhNS4CnZiPwdBJKXpBR28AfV50fPB8+aHtpkaMRdS8vrr1Fm64XasI3ITJsnCYGqUlhwzgbEL5hj1rGekKvEhw="
